### ISSUE TITLE
error in try sample projects

### ISSUE THREAD

**Issue by wujunhan-yunfu** [ncbi-nlp/TeamTat#21]
When I click the button named try sample projects, I get an error and can't enter the sample page

**Comment by wujunhan-yunfu** [comment]
The error message is couldn't find project with 'ID' = 68，and occurs in the following files
app/models/project.rb:106:in `block in load_samples'
app/models/project.rb:87:in `load_samples'
app/controllers/projects_controller.rb:168:in `load_samples'
