### ISSUE TITLE
Text file uploads fail with an 'Unprocessable Entity' error and a model RangeError

### ISSUE THREAD

**Issue by moskalenko** [ncbi-nlp/TeamTat#37]
Uploading a text file to a local instance of Teamtat throws an 'Unprocessable Entity' error.

Turning logging up to debug seems to point to the database structure:

D, [2023-01-27T10:20:14.652492 #30903] DEBUG -- : [78ab578b-a460-467e-a69e-b4d8a4fd561f] #<ActiveModel::RangeError: 2301271020 is out of range for ActiveMod
el::Type::Integer with limit 4 bytes>
D, [2023-01-27T10:20:14.652547 #30903] DEBUG -- : [78ab578b-a460-467e-a69e-b4d8a4fd561f] /var/www/TeamTat/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.4.2/
lib/active_model/type/integer.rb:53:in `ensure_in_range'
/var/www/TeamTat/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.4.2/lib/active_model/type/integer.rb:29:in `serialize'
/var/www/TeamTat/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.4.2/lib/active_model/attribute.rb:55:in `value_for_database'
...

**Comment by moskalenko** [comment]
The error comes up from any batch upload of a single ascii text file e.g. https://github.com/ncbi-nlp/TeamTat/files/10369086/document_ASCII_only.txt

**Comment by moskalenko** [comment]
I'd be happy to get on zoom and show you the error and the app debug log with db queries in real time if it helps.

**Comment by dongseop** [comment]
Could you try to upload the file again? I could upload the file successfully.
Recently, we fixed several bugs and it must be resolved with those patches.
